Add ament_cmake build_type export in package.xml and install package.xml file
open-dynamic-robot-initiative/master-board pull request #134
Opened 2023-06-22 05:15 UTC by olivier-stasse

[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Descrition

[//]: # "Description of what you did.  If it is more complex, consider to add a"
[//]: # "'Summary' section."
This PR is mostly to make the package ```master_board_xml``` more compliant to ROS-2.
It allows to have a better ROS-2 settings by:
- Add ```ament_cmake```build_type in the file ```package.xml```. Not doing this will prevent ```colcon``` to create the hooks for having the package  in the ROS-2  environment variables.
- Add installation procedure in ```CMakeLists.txt```

## How I Tested

[//]: # "Explain how you tested your changes"
This does not affect the other tests.
Checked if ```package.xml``` was installed, and did:
```
colcon build --packages-select master_board_sdk --cmake-args ' -DCMAKE_BUILD_TYPE=RELEASE'
export COLCON_STRACE=1
source ./install/setup.zsh
```
```master_board_sdk``` appears in ```AMENT_CMAKE_PATH```

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [X] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings). Used pre-commit
- [X] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

2023-06-23 14:59 UTC, nim65s requested changes
This strategy requires ROS 2 tools to be available in order to get an installed package which is compliant with ROS 2.

In eigenpy/hpp-fcl/pinocchio, this is not a requirement.

Could you elaborate on this design choice, and provide the limitations you faced while tring to implement the same logic as in eigenpy/hpp-fcl/pinocchio ?

2023-06-23 15:38 UTC, MaximilienNaveau commented on sdk/master_board_sdk/CMakeLists.txt
> +  ament_package()
if this overwrites the master-board-sdkConfig.cmake we could have issues with the downstream dependencies as jrl-cmakemodules properly writes the dependecies in the Config.cmake.

But for ament to do so you need to call another ament function, I believ it's `ament_export_dependencies(blabla)`.

Maybe you already checked that.

2023-06-23 16:49 UTC, olivier-stasse commented
> This strategy requires ROS 2 tools to be available in order to get an installed package which is compliant with ROS 2.
> 
> In eigenpy/hpp-fcl/pinocchio, this is not a requirement.
> 
> Could you elaborate on this design choice, and document the limitations you faced while tring to implement the same logic as in eigenpy/hpp-fcl/pinocchio ?
My initial evaluation was to build master_board_sdk and odri_control_interface in a colcon workspace.
I did this PR based on tests done without updating the CMake version.
Retesting the eigenpy/hpp-fcl/pinocchio approach with a proper CMake version, the use case I was testing is working smoothly. 
Thus I will make the changes accordingly.
But the lines added are the same all over the repositories. It might be worth to include them in jrl-cmakemodules.

2023-06-27 07:56 UTC, MaximilienNaveau approved these changes
Sounds good to me

2023-06-27 07:56 UTC, MaximilienNaveau commented on sdk/master_board_sdk/CMakeLists.txt
> +# --- Call ROS-2 if possible ---
this is not accurate anymore, yes?

2023-06-27 08:48 UTC, nim65s commented on sdk/master_board_sdk/CMakeLists.txt
> +# --- Call ROS-2 if possible ---
```suggestion
# --- Call ROS-2 if possible ---
```

2023-06-27 08:49 UTC, nim65s approved these changes

2023-06-27 08:49 UTC, merged

2023-06-27 09:23 UTC, olivier-stasse commented
Thanks @nim65s